version: '3.9'

services:
  postgres-container:
    image: postgres:12.1-alpine
    container_name: postgres-container-sensor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensor
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - delivery-network

  spring-boot-container:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres-container:5432/sensor
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.flyway.enabled=true
      - spring.flyway.baseline-on-migrate=true
    ports:
      - "8080:8080"
    networks:
      - delivery-network
    depends_on:
      - postgres-container

  flyway-migrate-dmp:
    image: flyway/flyway:7.7.0
    volumes:
      - ./migrations/dmp:/flyway/sql
    command: -url=jdbc:postgresql://postgres-container:5432/dmp?ssl=require -user=postgres -password=postgres -connectRetries=60 migrate
    networks:
      - delivery-network
    depends_on:
      - postgres-container

  flyway-migrate-lsm:
    image: flyway/flyway:7.7.0
    volumes:
      - ./migrations/lsm:/flyway/sql
    command: -url=jdbc:postgresql://postgres-container:5432/lsm?ssl=require -user=postgres -password=postgres -connectRetries=60 migrate
    networks:
      - delivery-network
    depends_on:
      - postgres-container

volumes:
  db_data:

networks:
  delivery-network:
    driver: bridge