version: '3.9'

services:
  postgres-container:
    image: kartoza/postgis:latest
    container_name: postgres-container-sensor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensor
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - delivery-network

  spring-boot-container:
    build:
      context: ./SensorApp
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:postgresql://postgres-container:5432/sensor
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      security.jwt.secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    ports:
      - "8080:8080"
    volumes:
      - /h/IT/Java/Проэкт/SensorApp/target:/sensorapp
    networks:
      - delivery-network
    depends_on:
      - postgres-container

volumes:
  db_data:

networks:
  delivery-network:
    driver: bridge